### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by PaigeSam** [stephantul/old20#10]
Hi Stephan!
Here is my word list, when I run it it goes into an infinite loop for some reason. Any help in debugging it would be appreciated.
```

import numpy as np
from old20 import old20, old_n

wordlist = open("mywords.txt").readlines()

print(len(wordlist))
words_neighborhood = old20(wordlist)
```

[mywords.txt](https://github.com/stephantul/old20/files/9572316/mywords.txt)

Kind regards
Paige

**Comment by stephantul** [comment]
Hi! 

I don't see an issue. It took a minute to run, but I got scores for all the words. I attached them in CSV format. I'm guessing this might be a Windows/Multiprocessing issue, which I can't readily solve. If you want, you can try again using:

```
words_neighborhood = old20(wordlist, n_jobs=1)
```

This disables multiprocessing.

BTW: this package calculates the OLD20 score as the sum of all neighbors, not the mean. So if you want "true" old20 scores, you can just divide all scores by 20. For regression analyses, this doesn't change anything.

Let me know if there's other stuff you run into.
Stéphan

[wordlist_with_scores.csv](https://github.com/stephantul/old20/files/9578204/wordlist_with_scores.csv)

**Comment by PaigeSam** [comment]
Thank you very much for the help, really appreciate it!

-Paige
